# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Laura
tagline:             'I made a blog. Check me out'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://lauracarter.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Laura
  url:              
  email:             

# Custom vars
version:             1.0.0
