# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Laura Carter
tagline:             'Gender, data, and human rights'
description:         ''
url:                 https://lauracarter.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Laura
  url:              
  email:             

# Custom vars
version:             1.0.0
